=== UO289510/sew/xml/circuito.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uniovi.es"
	xmlns="http://www.uniovi.es"
	elementFormDefault="qualified">

<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="caracteristicas" />
				<xs:element ref="carrera" />
				<xs:element ref="referencias" />
				<xs:element ref="galeria" />
				<xs:element ref="coordenadas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="caracteristicas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="caracteristica" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="caracteristica">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="nombre" type="xs:string" use="required" />
					<xs:attribute name="longitud" type="xs:integer" use="required" />
					<xs:attribute name="anchura" type="xs:integer" use="required" />
					<xs:attribute name="localidad" type="xs:string" use="required" />
					<xs:attribute name="pais" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="carrera">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="infoCarrera" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="infoCarrera">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="dato" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="dato">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="fecha" type="xs:date" use="required" />
					<xs:attribute name="hora" type="xs:time" use="required" />
					<xs:attribute name="vueltas" type="xs:integer" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="enlace" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="galeria">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto">
		<xs:complexType>
			<xs:attribute name="imagen" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:notation name="png" public="" system="imagen/png" />
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="salida" />
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="salida">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="latitud" type="xs:string" use="required" />
					<xs:attribute name="longitud" type="xs:string" use="required" />
					<xs:attribute name="altitud" type="xs:integer" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="distancia" type="xs:decimal" use="required" />
					<xs:attribute name="latitud" type="xs:string" use="required" />
					<xs:attribute name="longitud" type="xs:string" use="required" />
					<xs:attribute name="altitud" type="xs:integer" use="required" />
					<xs:attribute name="sector" type="xs:integer" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== UO289510/sew/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>


<circuito
xmlns="http://www.uniovi.es" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.uniovi.es circuito.xsd"> 
    <caracteristicas>
        <caracteristica nombre="Circuito Internacional de Losail"
         longitud="5380"
         anchura="12"
         localidad="Losail"
         pais="Qatar"
        />
    </caracteristicas>

    <carrera>
        <infoCarrera>
           <dato fecha="2024-11-29"
                hora="19:00:00"
                vueltas="57"/>
        </infoCarrera>
    </carrera>

    <referencias>
        <referencia enlace="https://www.dazn.com/es-ES/news/motor/circuito-losail-donde-esta-como-es-caracteristicas-llegar-fotos-escenario-gp-qatar-mundial-f1-motogp/a6znflaka6np1p41ckoiz6f7j"/> 
        <referencia enlace="https://en.wikipedia.org/wiki/Lusail_International_Circuit"/>
        <referencia enlace="https://www.circuitlosail.com/"/>
    </referencias>

    <galeria>
        <foto imagen="mapa.png"/>
    </galeria>

    <coordenadas>
        <salida latitud="25º 29' 12'' N"
                longitud="51º 27' 03'' E"
                altitud="12"/>
        
        <tramo distancia="430.03"
                latitud="25º 29' 33''N"
                longitud="51º 26' 51''E"
                altitud="11"
                sector="1"/>
        
        <tramo distancia="280.39"
                latitud="25º 29' 35''N"
                longitud="51º 26' 55''E"
                altitud="11"
                sector="1"/>

        <tramo distancia="140.37"
                latitud="25º 29' 33''N"
                longitud="51º 26' 59''E"
                altitud="10"
                sector="1"/>
                
        <tramo distancia="141.65"
                latitud="25º 29' 35''N"
                longitud="51º 27' 02''E"
                altitud="11"
                sector="1"/>

        <tramo distancia="96.49"
                latitud="25º 29' 38''N"
                longitud="51º 27' 02''E"
                altitud="11"
                sector="1"/>

        <tramo distancia="119.66"
                latitud="25º 29' 41''N"
                longitud="51º 27' 03''E"
                altitud="11"
                sector="1"/>

        <tramo distancia="290.54"
                latitud="25º 29' 49''N"
                longitud="51º 27' 12''E"
                altitud="10"
                sector="1"/>

        <tramo distancia="115.33"
                latitud="25º 29' 49''N"
                longitud="51º 27' 11''E"
                altitud="10"
                sector="1"/>

        <tramo distancia="75.45"
                latitud="25º 29' 47''N"
                longitud="51º 27' 16''E"
                altitud="10"
                sector="1"/>

        <tramo distancia="92.96"
                latitud="25º 29' 44''N"
                longitud="51º 27' 16''E"
                altitud="11"
                sector="1"/>

        <tramo distancia="111.59"
                latitud="25º 29' 41''N"
                longitud="51º 27' 13''E"
                altitud="11"
                sector="1"/>

        <tramo distancia="99.73"
                latitud="25º 29' 39''N"
                longitud="51º 27' 11''E"
                altitud="11"
                sector="2"/>

        <tramo distancia="91"
                latitud="25º 29' 38''N"
                longitud="51º 27' 12''E"
                altitud="12"
                sector="2"/>

        <tramo distancia="275.94"
                latitud="25º 29' 41''N"
                longitud="51º 27' 22''E"
                altitud="12"
                sector="2"/>

        <tramo distancia="200.07"
                latitud="25º 29' 37''N"
                longitud="51º 27' 23''E"
                altitud="12"
                sector="2"/>

        <tramo distancia="178.68"
                latitud="25º 29' 32''N"
                longitud="51º 27' 20''E"
                altitud="11"
                sector="2"/>

        <tramo distancia="98.65"
                latitud="25º 29' 30''N"
                longitud="51º 27' 18''E"
                altitud="11"
                sector="2"/>

        <tramo distancia="121.02"
                latitud="25º 29' 29''N"
                longitud="51º 27' 13''E"
                altitud="11"
                sector="2"/>

        <tramo distancia="116.87"
                latitud="25º 29' 26''N"
                longitud="51º 27' 13''E"
                altitud="11"
                sector="2"/>

        <tramo distancia="375.77"
                latitud="25º 29' 24''N"
                longitud="51º 27' 24''E"
                altitud="12"
                sector="2"/>

        <tramo distancia="121.33"
                latitud="25º 29' 22''N"
                longitud="51º 27' 33''E"
                altitud="12"
                sector="3"/>

        <tramo distancia="109.8"
                latitud="25º 29' 22''N"
                longitud="51º 27' 33''E"
                altitud="12"
                sector="3"/>

        <tramo distancia="103.16"
                latitud="25º 29' 19''N"
                longitud="51º 27' 35''E"
                altitud="12"
                sector="3"/>

        <tramo distancia="88.62"
                latitud="25º 29' 20''N"
                longitud="51º 27' 34''E"
                altitud="12"
                sector="3"/>

        <tramo distancia="126.7"
                latitud="25º 29' 13''N"
                longitud="51º 27' 32''E"
                altitud="13"
                sector="3"/>

        <tramo distancia="80.3"
                latitud="25º 29' 12''N"
                longitud="51º 27' 30''E"
                altitud="13"
                sector="3"/>

        <tramo distancia="233.33"
                latitud="25º 29' 14''N"
                longitud="51º 27' 22''E"
                altitud="13"
                sector="3"/>

        <tramo distancia="104.77"
                latitud="25º 29' 12''N"
                longitud="51º 27' 19''E"
                altitud="13"
                sector="3"/>

        <tramo distancia="342.34"
                latitud="25º 29' 02''N"
                longitud="51º 27' 13''E"
                altitud="13"
                sector="3"/>

        <tramo distancia="135.4"
                latitud="25º 29' 02''N"
                longitud="51º 27' 09''E"
                altitud="14"
                sector="3"/>

        <tramo distancia="643.62"
                latitud="25º 29' 21''N"
                longitud="51º 26' 58''E"
                altitud="12"
                sector="3"/>
        
    </coordenadas>

</circuito>
